                    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jFrame;

import diu.swe.habib.JavaToast.JToast;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author upeks
 */
public class LoginPage extends javax.swing.JFrame {
    
    /**
     * Creates new form LoginPage
     */
    
    Color darkblueColor = new Color(0,51,102);
    public LoginPage() {
        initComponents();
        lbl_InCorrectPassword1.setVisible(false);
        lbl_InCorrectUsername1.setVisible(false);
    }
    
    //ligin validation
    public boolean validateLogin(){
        
        String username = txt_username.getText();
        String password = txt_password.getText();
        
        if (username.isEmpty() && password.isEmpty()) {
            lbl_InCorrectUsername1.setVisible(true);
            lbl_InCorrectUsername1.setText("Enter username");
            lbl_InCorrectPassword1.setVisible(true);
            lbl_InCorrectPassword1.setText("Enter Password");
            return false;
        }
        if (username.isEmpty()) {
            //new JToast().makeToast(this, "please enter username", 1);
            //JOptionPane.showMessageDialog(this,"please enter username");
            lbl_InCorrectUsername1.setVisible(true);
            lbl_InCorrectUsername1.setText("Enter username");
            return false;
        }
        if (password.isEmpty()) {
            //new JToast().makeToast(this, "please enter password", 1);
            //JOptionPane.showMessageDialog(this,"please enter password");
            lbl_InCorrectPassword1.setVisible(true);
            lbl_InCorrectPassword1.setText("Enter Password");
            return false;
        }
        return true;
    }
    
    //find the user type
    public String userType(){
        String usertype = "";
        int userTypeIndex = CBox_userType.getSelectedIndex();
        if (userTypeIndex == 0) {
            usertype = "Librarian";
        }
        else{
            usertype = "Member";
        }
        return usertype;
    }
    
    //login
    public void login() {
    String username = txt_username.getText();
    String password = txt_password.getText();
    String usertypeDB = "";
    String NIC = null;
    
    try {
        Connection con = DBConnection.getConnection();
        PreparedStatement pst = con.prepareStatement("SELECT * FROM tbl_user WHERE username = ? AND password = ?");
        pst.setString(1, username);
        pst.setString(2, password);
        
        ResultSet rs = pst.executeQuery();
        
        if (rs.next()) {
            usertypeDB = rs.getString("user_Type");
            String userType = userType();
            
            if (usertypeDB.equals(userType)) {
                //JOptionPane.showMessageDialog(this,"Login successful");
                new JToast().makeToast(this, "Login successful", 1);
                
                if (userType.equals("Librarian")) {
                    HomePage1 home = new HomePage1();
                    home.setVisible(true);
                    this.dispose();
                } else if (userType.equals("Member")) {
                    NIC = rs.getString("NIC"); // Get the member ID from the ResultSet
                    SearchBooks searchBook = new SearchBooks(NIC); // Pass the member ID to the constructor
                    searchBook.setVisible(true);
                    this.dispose();
                }   
            } else {
                JOptionPane.showMessageDialog(this,"Invalid Login !","",JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,"Incorrect username or password","",JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSButtonMetroBeanInfo1 = new rojerusan.RSButtonMetroBeanInfo();
        rSButtonMetroBeanInfo2 = new rojerusan.RSButtonMetroBeanInfo();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl__password = new javax.swing.JLabel();
        lbl_userType = new javax.swing.JLabel();
        lbl_InCorrectPassword1 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        CBox_userType = new javax.swing.JComboBox<>();
        txt_password = new javax.swing.JPasswordField();
        lbl_usertypeicon = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        lbl_pw = new javax.swing.JLabel();
        btn_Login = new rojerusan.RSMaterialButtonRectangle();
        btn_exit = new rojerusan.RSMaterialButtonRectangle();
        lbl_username1 = new javax.swing.JLabel();
        lbl_InCorrectUsername1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(0, 51, 102)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Login");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 150, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Login with your credentiols");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 160, 30));

        lbl__password.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        lbl__password.setForeground(new java.awt.Color(153, 153, 153));
        lbl__password.setText("Password :");
        jPanel1.add(lbl__password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        lbl_userType.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        lbl_userType.setForeground(new java.awt.Color(0, 51, 102));
        lbl_userType.setText("User Type :");
        jPanel1.add(lbl_userType, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 120, -1));

        lbl_InCorrectPassword1.setFont(new java.awt.Font("Californian FB", 1, 12)); // NOI18N
        lbl_InCorrectPassword1.setForeground(new java.awt.Color(255, 0, 51));
        lbl_InCorrectPassword1.setText("!");
        jPanel1.add(lbl_InCorrectPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 110, -1));

        txt_username.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        txt_username.setForeground(new java.awt.Color(153, 153, 153));
        txt_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        txt_username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 250, -1));

        CBox_userType.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        CBox_userType.setForeground(new java.awt.Color(153, 153, 153));
        CBox_userType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Member" }));
        CBox_userType.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 102)));
        CBox_userType.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CBox_userTypeFocusGained(evt);
            }
        });
        jPanel1.add(CBox_userType, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 250, -1));

        txt_password.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        txt_password.setForeground(new java.awt.Color(153, 153, 153));
        txt_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 204)));
        txt_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_passwordFocusLost(evt);
            }
        });
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 250, -1));

        lbl_usertypeicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/users-32.png"))); // NOI18N
        jPanel1.add(lbl_usertypeicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        lbl_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-username-32gray.png"))); // NOI18N
        jPanel1.add(lbl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, 30));

        lbl_pw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-password-25gray.png"))); // NOI18N
        jPanel1.add(lbl_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        btn_Login.setBackground(new java.awt.Color(0, 51, 102));
        btn_Login.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 1, new java.awt.Color(51, 204, 255)));
        btn_Login.setText("LOGIN");
        btn_Login.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btn_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoginActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 140, 60));

        btn_exit.setBackground(new java.awt.Color(0, 51, 102));
        btn_exit.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 5, 1, new java.awt.Color(51, 204, 255)));
        btn_exit.setText("EXIT");
        btn_exit.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, 140, 60));

        lbl_username1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        lbl_username1.setForeground(new java.awt.Color(153, 153, 153));
        lbl_username1.setText("Username :");
        jPanel1.add(lbl_username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        lbl_InCorrectUsername1.setFont(new java.awt.Font("Californian FB", 1, 12)); // NOI18N
        lbl_InCorrectUsername1.setForeground(new java.awt.Color(255, 0, 51));
        lbl_InCorrectUsername1.setText("!");
        jPanel1.add(lbl_InCorrectUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 110, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 440, 610));

        jLabel1.setBackground(new java.awt.Color(0, 204, 255));
        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/signup-library-icon.png"))); // NOI18N
        jLabel1.setText("Public Library - Omalpe ");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 0, new java.awt.Color(0, 51, 102)));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 610));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void txt_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusGained
        lbl_InCorrectPassword1.setVisible(false);
        Color blueColor = new Color(51,204,255);
        
        Border border = BorderFactory.createMatteBorder(0, 0, 2, 0, darkblueColor);
        Icon userIconp = new ImageIcon("C:\\Users\\upeks\\Documents\\My stuffs\\project\\Year1-Sem2\\icons\\icons8-password-25.png");
        lbl__password.setForeground(darkblueColor);
        txt_password.setBorder(border);
        lbl_pw.setIcon(userIconp);
    }//GEN-LAST:event_txt_passwordFocusGained

    private void txt_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusLost
        if (txt_password.getText().trim().isEmpty()) {
            Color originalColor = new Color(204,204,204);
            Border border = BorderFactory.createMatteBorder(0, 0, 2, 0, originalColor);
            Icon userIconp = new ImageIcon("C:\\Users\\upeks\\Documents\\My stuffs\\project\\Year1-Sem2\\icons\\icons8-password-25gray.png");
            lbl__password.setForeground(originalColor);
            txt_password.setBorder(border);
            lbl_pw.setIcon(userIconp);
        }
        
    }//GEN-LAST:event_txt_passwordFocusLost

    private void CBox_userTypeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CBox_userTypeFocusGained
        CBox_userType.setForeground(Color.red);
    }//GEN-LAST:event_CBox_userTypeFocusGained

    private void btn_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoginActionPerformed
        if(validateLogin()){
            login();
            
        }
    }//GEN-LAST:event_btn_LoginActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_exitActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
        if (txt_username.getText().trim().isEmpty()){
            Color originalColor = new Color(204,204,204);
            Border border = BorderFactory.createMatteBorder(0, 0, 2, 0, originalColor);
            Icon userIcon = new ImageIcon("C:\\Users\\upeks\\Documents\\My stuffs\\project\\Year1-Sem2\\icons\\icons8-username-32gray.png");
            lbl_username1.setForeground(originalColor);
            lbl_user.setIcon(userIcon);
            txt_username.setBorder(border);
        }
    }//GEN-LAST:event_txt_usernameFocusLost

    private void txt_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusGained
        lbl_InCorrectUsername1.setVisible(false);
        Color blueColor = new Color(51,204,255);
        Border border = BorderFactory.createMatteBorder(0, 0, 2, 0, darkblueColor);
        Icon userIcon = new ImageIcon("C:\\Users\\upeks\\Documents\\My stuffs\\project\\Year1-Sem2\\icons\\username-32darkblue.png");
        lbl_username1.setForeground(darkblueColor);
        txt_username.setBorder(border);
        lbl_user.setIcon(userIcon);
    }//GEN-LAST:event_txt_usernameFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBox_userType;
    private rojerusan.RSMaterialButtonRectangle btn_Login;
    private rojerusan.RSMaterialButtonRectangle btn_exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_InCorrectPassword1;
    private javax.swing.JLabel lbl_InCorrectUsername1;
    private javax.swing.JLabel lbl__password;
    private javax.swing.JLabel lbl_pw;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JLabel lbl_userType;
    private javax.swing.JLabel lbl_username1;
    private javax.swing.JLabel lbl_usertypeicon;
    private rojerusan.RSButtonMetroBeanInfo rSButtonMetroBeanInfo1;
    private rojerusan.RSButtonMetroBeanInfo rSButtonMetroBeanInfo2;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
